### PR TITLE
provide overloaded methods for sample

### PR DESCRIPTION
**Pull request by oliverw1**
The `fraction` is a required argument to the `sample` method. Anytime someone calls `df.sample(.01)` this is met in mypy with 
> Argument 1 to "sample" of "DataFrame" has incompatible type "float"; expected "Optional[bool]"

In the Pyspark API, the three arguments are in fact pure keyword arguments that are handled later to ensure `fraction` must be given. This is probably done to keep consistent with the Scala API. 

By overloading the methods, the issue is resolved.

### CODE REVIEW

**Comment by oliverw1** [comment]
You're right, I did not see that. Good suggestion! 

I'll add the tests this weekend. Thanks for checking!

**Comment by oliverw1** [comment]
Updated. Note that travis isn't properly checking the outcome of Black. On my system, it hints at a missing comma in a file unrelated to this PR. Something to look at.

**Comment by zero323** [comment]
> Updated. Note that travis isn't properly checking the outcome of Black. On my system, it hints at a missing comma in a file unrelated to this PR. Something to look at.

Thanks for working on this. Looks good, but I'll double check thing in the next few days.

**Comment by zero323** [comment]
LGTM. Merged into master and backported to 2.4. 

Thank you @oliverw1!

**Pull request merged**
