### PR TITLE
Add `udf` overload to support decorators with named returnType

### PR DESCRIPTION
**Pull request by pgrz**
The `udf` decorator accepts `returnType` as an argument

### CODE REVIEW

**Review by zero323 — COMMENTED** [review]
Thank your for your proposal @pgrz.

If I understand correctly, you're trying to match following scenarios

```python
@udf(returnType="string")
def f(x):
   return x
```
Is that right?

**Comment by pgrz** [comment]
Yes - be it `"string"` or `StringType()`.

**Comment by zero323** [comment]
OK, that's a different case. Variant you're replacing

```python
def udf(
    f: DataTypeOrString = ...,
) -> Callable[[Callable[..., Any]], Callable[..., Column]]: ...
```
covers situations when you call `udf` with positional argument.

```python
@udf("string")
def f(x):
   return x
```

or, albeit that's not likely:

```python
@udf(f="string")
def f(x):
   return x
```

To match your intended pattern, we'd need a separate keyword-only variant:

```python
@overload
def udf(
   *,  returnType: DataTypeOrString = ...,
) -> Callable[[Callable[..., Any]], Callable[..., Column]]: ...
```

**Comment by pgrz** [comment]
Seems about right, thank you. I'm closing this pull request then, please consider adding the variant you proposed

**Comment by zero323** [comment]
Oh, I didn't mean that it should be closed ‒ just it might require more complex approach (and probably a few additional data tests) :)

If you want to keep working on that, feel free to adjust / reopen the PR.

**Comment by pgrz** [comment]
I misunderstood that, I'll work on it gladly :)

**Comment by zero323** [comment]
I am not sure there's no link to travis build so let me add it manually https://travis-ci.org/github/zero323/pyspark-stubs/builds/755491519

There are two things to fix:

- We don't allow re-definition for clarity so you'll have to use different names for functions within single test block.
- You have add import for `IntegerType`, within the legacy test block.

Additionally, could you add test for argumentless decorator and lambda?


```
udf(lambda x: x)

@udf
def h(x):
    return x
```

**Comment by zero323** [comment]
LGTM, subject to passing [travis tests](https://travis-ci.org/github/zero323/pyspark-stubs/builds/755531234) (I've already tested locally)/.

I'll handle porting to 3.0 here, but we should also forward-port this to upstream Spark repository. I've created a JIRA ticket ([SPARK-34191](https://issues.apache.org/jira/browse/SPARK-34191)). Would you mind creating a PR for this?


FYI @HyukjinKwon

**Comment by zero323** [comment]
Thanks @pgrz. Merged to 2.4 and ported to 3.0

**Pull request merged**
