### PR TITLE
Update distinct() and repartition() definitions

### PR DESCRIPTION
**Pull request by zpencerq**
Update repartition functions to allow for Col in `numPartitions` parameter.

[Reference](https://spark.apache.org/docs/latest/api/python/pyspark.sql.html#pyspark.sql.DataFrame.repartition)
```
numPartitions – can be an int to specify the target number of partitions or a Column.
    If it is a Column, it will be used as the first partitioning column.
    If not specified, the default number of partitions is used.
```

Also add stub for `DataFrame#distinct()`

### CODE REVIEW

**Comment by zero323** [comment]
Thanks for the PR @zpencerq!

I think that [`overloading`](https://docs.python.org/3/library/typing.html#typing.overload) definitions would be more appropriate than  `Union`. Logically these are two different signatures, and the meaning of the `Column` argument is quite different from a numeric one.

**Comment by zpencerq** [comment]
Ah, good point. I updated it in 18bced3a812cb9484f2181e454334886910f24da to reflect that. :+1:

**Comment by zero323** [comment]
I guess `repartitionByRange` should be overloaded as well, shouldn't it?

**Comment by zpencerq** [comment]
Might as well take care of that while we're at it. 5b1b526618da9f95e951862cfa65bddd2d98dbce

**Comment by zero323** [comment]
Looks good, merging into master.

Thanks for your work @zpencerq!

**Pull request merged**
